In [1]:
import sqlite3

# Replace 'your_file.sdb' with the actual SQLite database file path
db_file = '../data/model_ifc.sdb'

try:
    # Connect to the SQLite database
    conn = sqlite3.connect(db_file)

    # Create a cursor object to execute SQL queries
    # Create a cursor object to execute SQL queries
    cursor = conn.cursor()
    # Query the sqlite_master table to get the list of all tables
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")

    # Fetch the results
    tables = cursor.fetchall()

    # Extract table names and print them
    for table in tables:
        print(table[0])

except sqlite3.Error as e:
    print(f"SQLite error: {e}")
finally:
    # Close the database connection when done
    conn.close()

_objects_id
_objects_attr
_objects_val
_objects_eav

In [2]:
# Read data from _objects_attr
import pandas as pd
# Read data from _objects_id
conn = sqlite3.connect(db_file)
data_objects_id = pd.read_sql_query("SELECT * FROM _objects_id", conn)
data_objects_id.head(20)

    id        external_id  viewable_id
0    1                  a            1
1    2                  0            1
2    3                0/0            1
3    4              0/0/0            1
4    5            0/0/0/0            1
5    6            0/0/0/1            1
6    7            0/0/0/2            1
7    8            0/0/0/3            1
8    9            0/0/0/4            1
9   10          0/0/0/4/0            1
10  11        0/0/0/4/0/0            1
11  12      0/0/0/4/0/0/0            1
12  13    0/0/0/4/0/0/0/0            1
13  14  0/0/0/4/0/0/0/0/0            1
14  15  0/0/0/4/0/0/0/0/1            1
15  16        0/0/0/4/0/1            1
16  17      0/0/0/4/0/1/0            1
17  18        0/0/0/4/0/2            1
18  19      0/0/0/4/0/2/0            1
19  20    0/0/0/4/0/2/0/0            1

In [3]:
# Read data from _objects_attr
import pandas as pd
# Read data from _objects_id
data_objects_id = pd.read_sql_query("SELECT * FROM _objects_attr", conn)
data_objects_id.head(20)

,id,name,category,data_type,data_type_context,description,display_name,flags,display_precision,forge_parameter
0,1,name,__name__,20,None,None,None,0,0,None
1,2,child,__child__,11,None,None,None,1,0,None
2,3,parent,__parent__,11,None,None,None,1,0,None
3,4,instanceof_objid,__instanceof__,11,None,None,None,1,0,None
4,5,hastable,__hastable__,11,None,None,None,1,0,None
5,6,viewable_in,__viewable_in__,20,None,None,None,1,0,None
6,7,xref,__externalref__,20,None,None,None,1,0,None
7,8,is_doc_property,__document__,1,None,None,None,3,0,None
8,9,schema_name,__document__,20,None,None,None,1,0,None
9,10,schema_version,__document__,20,None,None,None,1,0,None
10,11,hyperlink,__hyperlink__,20,None,None,None,1,0,None
11,12,node_flags,__node_flags__,2,None,None,None,1,0,None
12,13,LcOaNode:LcOaSceneBaseUserName,Item,20,None,None,Name,0,0,None
13,14,LcOaNode:LcOaSceneBaseClassUserName,Item,20,None,None,Type,0,0,None
14,15,LcOaNode:LcOaNodeIcon,Item,21,None,None,Icon,0,0,None
15,16,LcOaNode:LcOaNodeHidden,Item,1,None,None,Hidden,0,0,None
16,17,LcOaNode:LcOaNodeRequired,Item,1,None,None,Required,0,0,None
17,18,LcOaNode:LcOaNodeMaterial,Item,20,None,None,Material,0,0,None
18,19,LcOaNode:LcOaUnit,Item,20,None,None,Unit,0,0,None
19,20,LcRevitPropertyProject:lcldrevit_parameter_-10...,Project,20,None,None,IfcApplicationName,0,0,None

In [4]:
# Read data from _objects_attr
import pandas as pd
# Read data from _objects_id
data_objects_id = pd.read_sql_query("SELECT * FROM _objects_val", conn)
data_objects_id.head(20)

    id                       value
0    1              MyHouseRCP.ifc
1    2                           5
2    3                        File
3    4                           0
4    5
5    6                 Millimeters
6    7   Autodesk Revit 2023 (ENU)
7    8                        2023
8    9               Location Data
9   10                   42.358662
10  11                   -71.05674
11  12                        -5.0
12  13                Default Site
13  14              IFC Properties
14  15  2023-08-25 08:58:17 +08:00
15  16                        IFC4
16  17   LcNwcLoaderPlugin:lcldifc
17  18                         nwd
18  19             Navisworks 2024
19  20                           1

In [5]:
# Read data from _objects_attr
import pandas as pd
# Read data from _objects_id
data_objects_id = pd.read_sql_query("SELECT * FROM _objects_eav", conn)
data_objects_id.head(20)

    id  entity_id  attribute_id  value_id
0    1          1             6         1
1    2          1             1         1
2    3          1            12         2
3    4          1            13         1
4    5          1            14         3
5    6          1            15         3
6    7          1            16         4
7    8          1            17         4
8    9          1            18         5
9   10          1            19         6
10  11          1            20         7
11  12          1            21         8
12  13          1            22         9
13  14          1            23        10
14  15          1            24        11
15  16          1            25         4
16  17          1            26        12
17  18          1            27        13
18  19          1            28        14
19  20          1            29         8

In [6]:
# Define and execute the SQL query with a JOIN statement
conn = sqlite3.connect(db_file)
# Define and execute the SQL query with JOIN statements
query = """
SELECT _objects_id.external_id, _objects_attr.category,_objects_attr.display_name, _objects_val.value
FROM _objects_id
JOIN _objects_eav ON _objects_id.id = _objects_eav.entity_id
JOIN _objects_attr ON _objects_eav.attribute_id = _objects_attr.id
JOIN _objects_val ON _objects_eav.value_id = _objects_val.id;
"""
data = pd.read_sql_query(query, conn)
data

,external_id,category,display_name,value
0,a,__viewable_in__,None,MyHouseRCP.ifc
1,a,__name__,None,MyHouseRCP.ifc
2,a,__node_flags__,None,5
3,a,Item,Name,MyHouseRCP.ifc
4,a,Item,Type,File
...,...,...,...,...
3738,1/0/1,Element,IfcGUID,3mTAi_OHnr$eH8uoAnekPh
3739,1/0/1,Element,IfcName,"Window-Casement-Double:48"" x 60"":299579:1"
3740,1/0/1,Element,IfcTag,299579
3741,1/0/1,__parent__,None,98
3742,1/0,__child__,None,100

In [34]:
# Query filter just Walls
conn = sqlite3.connect(db_file)
# Define and execute the SQL query with JOIN statements
query = """
SELECT _objects_id.external_id, _objects_attr.category,_objects_attr.display_name, _objects_val.value
FROM _objects_id
JOIN _objects_eav ON _objects_id.id = _objects_eav.entity_id
JOIN _objects_attr ON _objects_eav.attribute_id = _objects_attr.id
JOIN _objects_val ON _objects_eav.value_id = _objects_val.id
WHERE _objects_attr.category = 'Element' ;
"""
dfElement = pd.read_sql_query(query, conn)
dfElement.head(20)

,external_id,category,display_name,value
0,0,Element,IfcClass,IfcProject
1,0,Element,IfcGUID,0FGaRUnk56gx91laTC2BWX
2,0,Element,IfcName,SG_001
3,0,Element,Original IFC File Name,Z:\worker\viewing-ifc-lmv-cosv3\tmp\job-1\8\My...
4,0,Element,Original IFC File Size,18692208
5,0,Element,Revit File Last Updated,638285219636339083
6,0,Element,Revit Importer Version,Importer 24.0.3.416
7,0/0,Element,Elevation,0
8,0/0,Element,IfcClass,IfcSite
9,0/0,Element,IfcDecomposes,SG_001
10,0/0,Element,IfcDecomposesGUID,0FGaRUnk56gx91laTC2BWX
11,0/0,Element,IfcGUID,0FGaRUnk56gx91laTC2BWZ
12,0/0,Element,IfcName,Default
13,0/0,Element,IfcPropertySetList,"""Pset_SiteCommon"";""Identity Data"";""Other"""
14,0/0,Element,Latitude,0.739298
15,0/0,Element,Longitude,-1.240174
16,0/0/0,Element,IfcBuilding AddressLines,24-237 Singapore
17,0/0/0,Element,IfcBuilding Country,MA
18,0/0/0,Element,IfcBuilding Region,Boston
19,0/0/0,Element,IfcClass,IfcBuilding

# Chat with your Data

In [7]:
# %pip install --user langchain
# %pip instlal --user openai
# pip install --user tabulate

In [14]:
## chat with your data 
import pandas as pd
import os
import numpy as np
from langchain.document_loaders import DataFrameLoader

In [35]:
# Create an instance of DataFrameLoader
loader = DataFrameLoader(dfElement,page_content_column="category")
documents = loader.load()

In [36]:
from langchain.agents import create_pandas_dataframe_agent
from langchain.chat_models import ChatOpenAI
from langchain.agents.agent_types import AgentType
from langchain.llms import OpenAI
import pandas as pd

agent = create_pandas_dataframe_agent(OpenAI(temperature=0), dfElement, verbose=True)

In [37]:
agent = create_pandas_dataframe_agent(
    ChatOpenAI(temperature=0, model="gpt-3.5-turbo-0613"),
    data,
    verbose=True,
    agent_type=AgentType.OPENAI_FUNCTIONS,
)

In [38]:
agent.run("how many elements ?")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': 'df.shape[0]'}`


3743There are 3743 elements in the dataframe.

> Finished chain.

'There are 3743 elements in the dataframe.'

In [39]:
agent.run("How many categories of elements ?")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': "df['category'].nunique()"}`


73There are 73 categories of elements in the dataframe.

> Finished chain.

'There are 73 categories of elements in the dataframe.'

agent.run("h")

In [41]:
agent.run("show list categories of elements")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': "df['category'].unique().tolist()"}`


['__viewable_in__', '__name__', '__node_flags__', 'Item', 'Project', 'Location', 'IFC Properties', '__document__', 'Element ID', 'Element', '__parent__', '__child__', 'Identity Data', 'Other', 'Pset_SiteCommon', 'Pset_BuildingCommon', 'Pset_BuildingElementProxyCommon', 'Pset_BuildingStoreyCommon', 'Pset_BuildingSystemCommon', 'Constraints', 'Constraints(Type)', 'Dimensions', 'Graphics(Type)', 'Identity Data(Type)', 'Other(Type)', 'Constraints (IFC Type)', 'General (IFC Type)', 'Identity Data (IFC Type)', 'IFC Type', 'Other (IFC Type)', 'Pset_BuildingElementProxyCommon (IFC Type)', 'Phasing', 'Pset_EnvironmentalImpactIndicators', 'IFC Material', 'Dimensions (IFC Type)', 'Electrical (IFC Type)', 'Materials and Finishes (IFC Type)', 'Mechanical - Loads (IFC Type)', 'Mechanical (IFC Type)', 'Pset_ManufacturerTypeInformation (IFC Type)', 'Visibility (IFC Type)', 'Electrical', 'Mechanical', 'Visibility', 'Materials and Finishes', '__instanceof__', 'Construction (IFC Type)', 'Analytical Properties (IFC Type)', 'Pset_DoorCommon (IFC Type)', 'Classification: Uniformat', 'Pset_DoorCommon', 'Pset_FurnitureTypeCommon', 'Construction', 'Electrical - Loads (IFC Type)', 'Photometrics (IFC Type)', 'Pset_ElectricalDeviceCommon (IFC Type)', 'Electrical - Lighting', 'Pset_LightFixtureTypeCommon', 'Graphics (IFC Type)', 'Pset_SlabCommon (IFC Type)', 'Pset_ReinforcementBarPitchOfSlab', 'Pset_SlabCommon', 'Structural', 'Energy Analysis', 'Pset_SpaceCommon', 'Pset_SpaceHeaterTypeCommon', 'Pset_WallCommon (IFC Type)', 'Cross-Section Definition', 'Pset_ReinforcementBarPitchOfWall', 'Pset_WallCommon', 'Pset_WindowCommon (IFC Type)', 'Graphics', 'Pset_WindowCommon']The list of categories of elements in the dataframe is as follows:

- __viewable_in__
- __name__
- __node_flags__
- Item
- Project
- Location
- IFC Properties
- __document__
- Element ID
- Element
- __parent__
- __child__
- Identity Data
- Other
- Pset_SiteCommon
- Pset_BuildingCommon
- Pset_BuildingElementProxyCommon
- Pset_BuildingStoreyCommon
- Pset_BuildingSystemCommon
- Constraints
- Constraints(Type)
- Dimensions
- Graphics(Type)
- Identity Data(Type)
- Other(Type)
- Constraints (IFC Type)
- General (IFC Type)
- Identity Data (IFC Type)
- IFC Type
- Other (IFC Type)
- Pset_BuildingElementProxyCommon (IFC Type)
- Phasing
- Pset_EnvironmentalImpactIndicators
- IFC Material
- Dimensions (IFC Type)
- Electrical (IFC Type)
- Materials and Finishes (IFC Type)
- Mechanical - Loads (IFC Type)
- Mechanical (IFC Type)
- Pset_ManufacturerTypeInformation (IFC Type)
- Visibility (IFC Type)
- Electrical
- Mechanical
- Visibility
- Materials and Finishes
- __instanceof__
- Construction (IFC Type)
- Analytical Properties (IFC Type)
- Pset_DoorCommon (IFC Type)
- Classification: Uniformat
- Pset_DoorCommon
- Pset_FurnitureTypeCommon
- Construction
- Electrical - Loads (IFC Type)
- Photometrics (IFC Type)
- Pset_ElectricalDeviceCommon (IFC Type)
- Electrical - Lighting
- Pset_LightFixtureTypeCommon
- Graphics (IFC Type)
- Pset_SlabCommon (IFC Type)
- Pset_ReinforcementBarPitchOfSlab
- Pset_SlabCommon
- Structural
- Energy Analysis
- Pset_SpaceCommon
- Pset_SpaceHeaterTypeCommon
- Pset_WallCommon (IFC Type)
- Cross-Section Definition
- Pset_ReinforcementBarPitchOfWall
- Pset_WallCommon
- Pset_WindowCommon (IFC Type)
- Graphics
- Pset_WindowCommon

> Finished chain.

'The list of categories of elements in the dataframe is as follows:\n\n- __viewable_in__\n- __name__\n- __node_flags__\n- Item\n- Project\n- Location\n- IFC Properties\n- __document__\n- Element ID\n- Element\n- __parent__\n- __child__\n- Identity Data\n- Other\n- Pset_SiteCommon\n- Pset_BuildingCommon\n- Pset_BuildingElementProxyCommon\n- Pset_BuildingStoreyCommon\n- Pset_BuildingSystemCommon\n- Constraints\n- Constraints(Type)\n- Dimensions\n- Graphics(Type)\n- Identity Data(Type)\n- Other(Type)\n- Constraints (IFC Type)\n- General (IFC Type)\n- Identity Data (IFC Type)\n- IFC Type\n- Other (IFC Type)\n- Pset_BuildingElementProxyCommon (IFC Type)\n- Phasing\n- Pset_EnvironmentalImpactIndicators\n- IFC Material\n- Dimensions (IFC Type)\n- Electrical (IFC Type)\n- Materials and Finishes (IFC Type)\n- Mechanical - Loads (IFC Type)\n- Mechanical (IFC Type)\n- Pset_ManufacturerTypeInformation (IFC Type)\n- Visibility (IFC Type)\n- Electrical\n- Mechanical\n- Visibility\n- Materials and Finishes\n- __instanceof__\n- Construction (IFC Type)\n- Analytical Properties (IFC Type)\n- Pset_DoorCommon (IFC Type)\n- Classification: Uniformat\n- Pset_DoorCommon\n- Pset_FurnitureTypeCommon\n- Construction\n- Electrical - Loads (IFC Type)\n- Photometrics (IFC Type)\n- Pset_ElectricalDeviceCommon (IFC Type)\n- Electrical - Lighting\n- Pset_LightFixtureTypeCommon\n- Graphics (IFC Type)\n- Pset_SlabCommon (IFC Type)\n- Pset_ReinforcementBarPitchOfSlab\n- Pset_SlabCommon\n- Structural\n- Energy Analysis\n- Pset_SpaceCommon\n- Pset_SpaceHeaterTypeCommon\n- Pset_WallCommon (IFC Type)\n- Cross-Section Definition\n- Pset_ReinforcementBarPitchOfWall\n- Pset_WallCommon\n- Pset_WindowCommon (IFC Type)\n- Graphics\n- Pset_WindowCommon'